# include:
#   - compose.observability.yaml
services:
  speaches:
    extends:
      file: compose.yaml
      service: speaches
    image: ghcr.io/speaches-ai/speaches:cuda
    build:
      args:
        BASE_IMAGE: ${BASE_IMAGE:-nvidia/cuda:12.9.1-cudnn-runtime-ubuntu24.04}
    volumes:
      - ~/.huggingface:/home/ubuntu/.cache/huggingface
    devices:
      - nvidia.com/gpu=all
