# include:
#   - compose.observability.yaml
services:
  speaches:
    extends:
      file: compose.yaml
      service: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cuda-12.6.3
    build:
      args:
        BASE_IMAGE: ${BASE_IMAGE:-nvidia/cuda:13.0.2-cudnn-devel-ubuntu24.04}
    volumes:
      - ./huggingface:/home/ubuntu/.cache/huggingface/hub
    devices:
      - nvidia.com/gpu=all
